name: employee_management_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  hive: ^2.2.3
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  logger: ^2.0.2+1
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  table_calendar_null_safe: ^2.0.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/no_employee_records.png
    - assets/images/event.svg
    - assets/images/delete_icon.svg
    - assets/images/arrow_right.svg
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
